# .github/workflows/main.yml

name: macOS Remote Desktop (Final Ascension)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: '1. Install NoMachine and Forge SSH Key'
        run: |
          echo "Installing NoMachine..."
          curl -L -o nomachine.dmg https://download.nomachine.com/download/9.0/MacOSX/nomachine_9.0.188_11.dmg
          hdiutil attach nomachine.dmg
          MOUNT_PATH=$(ls /Volumes/ | grep NoMachine)
          PKG_PATH=$(find "/Volumes/$MOUNT_PATH" -name "*.pkg" | head -n 1)
          sudo installer -pkg "$PKG_PATH" -target /
          hdiutil detach "/Volumes/$MOUNT_PATH" || true # Add || true to ignore the eject error

          echo "Forging the Undeniable Key..."
          # Generate a new SSH key pair without a passphrase
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/nomachine_key -N ""
          
          # Authorize the new public key for the runner user
          cat ~/.ssh/nomachine_key.pub >> ~/.ssh/authorized_keys
          
          # Set correct permissions
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/authorized_keys
          
          echo "Key has been forged and authorized."

      - name: '2. Reveal the Private Key and Create Tunnel'
        run: |
          echo "--------------------------------------------------------------------"
          echo "ACTION REQUIRED: COPY THE PRIVATE KEY BELOW."
          echo "Save it to a file on your computer named 'github_key'. You will need it."
          echo "--------------------------------------------------------------------"
          
          # Display the private key in the log
          cat ~/.ssh/nomachine_key
          
          echo "--------------------------------------------------------------------"
          echo "PRIVATE KEY REVEALED. TUNNEL IS OPENING."
          echo "--------------------------------------------------------------------"

          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore
          nohup ./bore local 4000 --to bore.pub > tunnel.log 2>&1 &
          sleep 5
          cat tunnel.log
          
          sleep 21000
