# .github/workflows/macos-rdp.yml

name: macOS Remote Desktop (TigerVNC)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-12
    timeout-minutes: 350

    steps:
      - name: '1. Install and Configure TigerVNC'
        run: |
          echo "Installing TigerVNC..."
          brew install tiger-vnc

          echo "Configuring VNC password..."
          # Hide password from logs
          echo "::add-mask::${{ secrets.VNC_PASSWORD }}"
          
          # Create the .vnc directory and set the password
          mkdir -p ~/.vnc
          TIGERVNCPASSWD_PATH=$(brew --prefix tiger-vnc)/bin/tigervncpasswd
          echo "${{ secrets.VNC_PASSWORD }}" | $TIGERVNCPASSWD_PATH -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          echo "TigerVNC password configured."

      - name: '2. Start TigerVNC Server'
        run: |
          echo "Starting TigerVNC server..."
          # Start the server on display :1, which corresponds to port 5901.
          # -localhost no : Allows connections from outside the runner.
          # -SecurityTypes VncAuth : Use the standard VNC password authentication.
          # -PasswordFile : Specifies our created password file.
          # -fg : Runs the server in the foreground, keeping the job alive without needing a separate 'sleep' command.
          tigervncserver :1 -localhost no -SecurityTypes VncAuth -PasswordFile ~/.vnc/passwd &
          sleep 5 # Give the server a moment to initialize before tunneling.

      - name: '3. Create Tunnel with bore'
        run: |
          echo "Downloading and running bore..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore

          echo "Starting bore tunnel for VNC (port 5901)..."
          # Tunnel to port 5901, where TigerVNC is running.
          # We run this in the background so the final step can provide instructions.
          nohup ./bore local 5901 --to bore.pub > tunnel.log 2>&1 &
          sleep 5 # Wait for the tunnel address to be generated.
          
          echo "--------------------------------------------------------------------"
          echo "SESSION IS NOW ACTIVE."
          cat tunnel.log
          echo "--------------------------------------------------------------------"
          echo "Use the 'bore.pub:PORT' address from the log above."
          echo "Your VNC password is the one you set in the VNC_PASSWORD secret."
          echo "Username is not required for connection."
          echo "This session will remain active for approximately 6 hours."

      - name: '4. Keep Workflow Alive'
        run: |
          # The primary purpose of this step is to wait. The VNC and tunnel processes run in the background.
          sleep 21000
