# .github/workflows/main.yml

name: macOS Remote Desktop (The Final Gambit)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-12 # THE CRITICAL CHANGE: Target the Intel-based OS
    timeout-minutes: 350

    steps:
      - name: '1. Create User, Grant VNC, and Wake Display'
        run: |
          echo "::add-mask::${{ secrets.RDP_USER_PASSWORD }}"

          # Create the user 'rdpuser'. This is a reliable method.
          echo "Creating user 'rdpuser'..."
          sudo dscl . -create /Users/rdpuser
          sudo dscl . -create /Users/rdpuser UserShell /bin/bash
          sudo dscl . -create /Users/rdpuser RealName "RDP User"
          sudo dscl . -create /Users/rdpuser UniqueID "1001"
          sudo dscl . -passwd /Users/rdpuser "${{ secrets.RDP_USER_PASSWORD }}"
          sudo dscl . -append /Groups/admin GroupMembership rdpuser

          # Grant VNC privileges directly to the new user.
          echo "Granting VNC privileges to 'rdpuser'..."
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -users rdpuser -privs -all -restart -agent -menu

          # Force the login window to restart to initialize the display. This is likely to work on macos-12.
          echo "Forcing display to wake up by restarting the login window..."
          sudo pkill loginwindow

          echo "System is configured and ready."

      - name: '2. Create Tunnel and Provide Instructions'
        run: |
          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore

          echo "Starting bore tunnel for VNC (port 5900)..."
          nohup ./bore local 5900 --to bore.pub > tunnel.log 2>&1 &
          sleep 5

          echo "--------------------------------------------------------------------"
          echo "SESSION IS NOW ACTIVE. THE FINAL PATH IS OPEN."
          cat tunnel.log
          echo "--------------------------------------------------------------------"
          
          sleep 21000
