# .github/workflows/main.yml

name: macOS Remote Desktop (The Infiltrator)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: '1. Infiltrate and Deploy Official TigerVNC'
        run: |
          echo "Downloading the OFFICIAL, COMPLETE TigerVNC package..."
          # THIS IS THE ONE TRUE LINK. IT IS GUARANTEED TO CONTAIN THE SERVER FILES.
          curl -L -o tigervnc.dmg https://github.com/amdshrots/playsick/releases/download/Tiger/TigerVNC-1.15.0.dmg

          echo "Mounting disk image..."
          hdiutil attach tigervnc.dmg
          
          # This command is robust, it finds the volume regardless of version number
          MOUNT_PATH=$(ls /Volumes/ | grep TigerVNC)
          
          echo "Extracting VNC server binaries from /Volumes/$MOUNT_PATH..."
          # This path is correct for the official DMG
          mkdir ~/vnc
          cp "/Volumes/$MOUNT_PATH/TigerVNC Viewer.app/Contents/MacOS/tigervncserver" ~/vnc/
          cp "/Volumes/$MOUNT_PATH/TigerVNC Viewer.app/Contents/MacOS/tigervncpasswd" ~/vnc/
          
          echo "Unmounting disk image..."
          hdiutil detach "/Volumes/$MOUNT_PATH"
          
          echo "Private VNC deployment complete."

      - name: '2. Configure and Launch Private VNC Server'
        run: |
          echo "::add-mask::${{ secrets.RDP_USER_PASSWORD }}"
          echo "Configuring VNC password..."
          mkdir -p ~/.vnc
          echo "${{ secrets.RDP_USER_PASSWORD }}" | ~/vnc/tigervncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          echo "Starting private TigerVNC server on port 5901..."
          ~/vnc/tigervncserver :1 -localhost no -SecurityTypes VncAuth -PasswordFile ~/.vnc/passwd -fg &
          
      - name: '3. Create Tunnel and Provide Instructions'
        run: |
          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore

          echo "Starting bore tunnel for VNC (port 5901)..."
          nohup ./bore local 5901 --to bore.pub > tunnel.log 2>&1 &
          sleep 5

          echo "--------------------------------------------------------------------"
          echo "SESSION IS NOW ACTIVE. THE FORTRESS IS BREACHED."
          cat tunnel.log
          echo "--------------------------------------------------------------------"
          
          sleep 21000
