# .github/workflows/main.yml

name: macOS Remote Desktop (Final)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: '1. Prepare System and Enable VNC'
        run: |
          echo "Setting password for 'runner' user and creating 'rdpuser'..."
          echo "::add-mask::${{ secrets.RDP_USER_PASSWORD }}"
          
          # Set a known password for the existing 'runner' user
          sudo dscl . -passwd /Users/runner "${{ secrets.RDP_USER_PASSWORD }}"

          # Create a secondary user (this helps initialize the VNC service properly)
          sudo dscl . -create /Users/rdpuser
          sudo dscl . -create /Users/rdpuser UserShell /bin/bash
          sudo dscl . -create /Users/rdpuser RealName "RDP User"
          sudo dscl . -create /Users/rdpuser UniqueID "1001"
          sudo dscl . -passwd /Users/rdpuser "${{ secrets.RDP_USER_PASSWORD }}"
          sudo dscl . -append /Groups/admin GroupMembership rdpuser
          
          echo "Enabling and configuring built-in VNC Server..."
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on
          
          # THE CORRECTED SYNTAX: Use '-setvncpw -vncpw' as documented in the log
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw -vncpw "${{ secrets.RDP_USER_PASSWORD }}" -setvnclegacy -vnclegacy yes

          echo "VNC service is configured and active."

      - name: '2. Create Tunnel and Keep Alive'
        run: |
          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore

          echo "Starting bore tunnel for VNC (port 5900)..."
          nohup ./bore local 5900 --to bore.pub > tunnel.log 2>&1 &
          sleep 5

          echo "--------------------------------------------------------------------"
          echo "SESSION IS NOW ACTIVE. READ LOGIN INSTRUCTIONS CAREFULLY."
          cat tunnel.log
          echo "--------------------------------------------------------------------"
          
          sleep 21000
