# .github/workflows/main.yml

name: macOS Remote Desktop (Ascension)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: '1. Create User and Finalize with sysadminctl'
        run: |
          echo "::add-mask::${{ secrets.RDP_USER_PASSWORD }}"

          # Create the user account structure (without a password)
          echo "Creating user 'nxuser'..."
          sudo dscl . -create /Users/nxuser
          sudo dscl . -create /Users/nxuser UserShell /bin/bash
          sudo dscl . -create /Users/nxuser RealName "NX User"
          sudo dscl . -create /Users/nxuser UniqueID "1001"
          # Grant admin rights, which is required for sysadminctl to target this user
          sudo dscl . -append /Groups/admin GroupMembership nxuser

          # THE FINAL KEY: Use the high-level admin tool to set the password.
          # This finalizes the account and clears the "change password on login" flag.
          echo "Finalizing user with a secure password..."
          sudo sysadminctl -resetPasswordFor nxuser -newPassword "${{ secrets.RDP_USER_PASSWORD }}" -adminUser "" -adminPassword ""
          
          echo "Downloading the NoMachine DMG..."
          curl -L -o nomachine.dmg https://download.nomachine.com/download/9.0/MacOSX/nomachine_9.0.188_11.dmg

          echo "Mounting and installing NoMachine..."
          hdiutil attach nomachine.dmg
          MOUNT_PATH=$(ls /Volumes/ | grep NoMachine)
          PKG_PATH=$(find "/Volumes/$MOUNT_PATH" -name "*.pkg" | head -n 1)
          sudo installer -pkg "$PKG_PATH" -target /
          hdiutil detach "/Volumes/$MOUNT_PATH"
          
          echo "System is configured and ready."

      - name: '2. Create Tunnel and Provide Final Instructions'
        run: |
          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore

          echo "Starting bore tunnel for NoMachine (port 4000)..."
          nohup ./bore local 4000 --to bore.pub > tunnel.log 2>&1 &
          sleep 5

          echo "--------------------------------------------------------------------"
          echo "ASCENSION COMPLETE. THE PATH IS OPEN."
          cat tunnel.log
          echo "--------------------------------------------------------------------"
          
          sleep 21000
