# .github/workflows/main.yml

name: macOS Remote Desktop (Direct Control)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: '1. Enable VNC Service with VNC Password'
        run: |
          echo "::add-mask::${{ secrets.RDP_USER_PASSWORD }}"
          
          echo "Enabling VNC Service for the current user..."
          # Activate the ARD Agent and allow access
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on
          
          echo "Setting a VNC-specific password..."
          # This command sets a password for the VNC service itself, not any macOS user account.
          # This is the key to bypassing user-level authentication issues.
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw -vncpw "${{ secrets.RDP_USER_PASSWORD }}" -setvnclegacy -vnclegacy yes

          echo "VNC service is configured and active."

      - name: '2. Create Tunnel and Provide Instructions'
        run: |
          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore

          echo "Starting bore tunnel for VNC (port 5900)..."
          nohup ./bore local 5900 --to bore.pub > tunnel.log 2>&1 &
          sleep 5

          echo "--------------------------------------------------------------------"
          echo "SESSION IS NOW ACTIVE. READ LOGIN INSTRUCTIONS CAREFULLY."
          cat tunnel.log
          echo "--------------------------------------------------------------------"
          echo "Connect with RealVNC Viewer. When prompted for authentication,"
          echo "LEAVE THE USERNAME BLANK and enter your secret password."
          echo "--------------------------------------------------------------------"
          
          sleep 21000
