# .github/workflows/main.yml

name: macOS Remote Desktop (Definitive)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: '1. Install and Configure TigerVNC'
        run: |
          echo "Installing TigerVNC..."
          brew install tiger-vnc

          echo "Configuring VNC password..."
          if [ -z "${{ secrets.VNC_PASSWORD }}" ]; then
            echo "Error: VNC_PASSWORD secret is not set."
            exit 1
          fi
          echo "::add-mask::${{ secrets.VNC_PASSWORD }}"
          
          mkdir -p ~/.vnc
          
          # THE DEFINITIVE SOLUTION: Use the absolute path derived from 'brew --prefix'
          echo "${{ secrets.VNC_PASSWORD }}" | $(brew --prefix)/bin/tigervncpasswd -f > ~/.vnc/passwd
          
          chmod 600 ~/.vnc/passwd
          echo "TigerVNC password configured."

      - name: '2. Start VNC Server and Tunnel'
        run: |
          echo "Starting TigerVNC server..."
          # Use the absolute path for the server as well for maximum reliability
          $(brew --prefix)/bin/tigervncserver :1 -localhost no -SecurityTypes VncAuth -PasswordFile ~/.vnc/passwd &
          sleep 5

          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore
          
          nohup ./bore local 5901 --to bore.pub > tunnel.log 2>&1 &
          sleep 5

          echo "--------------------------------------------------------------------"
          echo "SESSION IS NOW ACTIVE."
          cat tunnel.log
          echo "--------------------------------------------------------------------"
          echo "Use the 'bore.pub:PORT' address from the log to connect."
          echo "Password is your VNC_PASSWORD secret. Username is not required."
          
          # Keep the job alive
          sleep 21000
