# .github/workflows/main.yml

name: macOS Remote Desktop (Ascension)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: '1. Create User and Install NoMachine'
        run: |
          echo "::add-mask::${{ secrets.RDP_USER_PASSWORD }}"

          # Create a user for NoMachine to authenticate
          echo "Creating user 'nxuser'..."
          sudo dscl . -create /Users/nxuser
          sudo dscl . -create /Users/nxuser UserShell /bin/bash
          sudo dscl . -create /Users/nxuser RealName "NX User"
          sudo dscl . -create /Users/nxuser UniqueID "1001"
          sudo dscl . -passwd /Users/nxuser "${{ secrets.RDP_USER_PASSWORD }}"
          sudo dscl . -append /Groups/admin GroupMembership nxuser

          echo "Downloading the NoMachine package..."
          # Download the official PKG installer for macOS
          curl -L -o nomachine.pkg https://download.nomachine.com/download/8.11/MacOSX/nomachine_8.11.3_1.pkg

          echo "Installing NoMachine..."
          # Use the native macOS installer. This is a robust method.
          sudo installer -pkg nomachine.pkg -target /
          
          echo "System is configured for NoMachine."

      - name: '2. Create Tunnel and Provide Final Instructions'
        run: |
          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore

          echo "Starting bore tunnel for NoMachine (port 4000)..."
          # NoMachine uses port 4000 by default
          nohup ./bore local 4000 --to bore.pub > tunnel.log 2>&1 &
          sleep 5

          echo "--------------------------------------------------------------------"
          echo "ASCENSION COMPLETE. A NEW PATH IS OPEN."
          cat tunnel.log
          echo "--------------------------------------------------------------------"
          
          sleep 21000
