# .github/workflows/main.yml

name: macOS Remote Desktop (DMG Inspector)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    steps:
      - name: '1. Download and Inspect Your DMG'
        run: |
          echo "Downloading the DMG from YOUR provided link..."
          curl -L -o tigervnc.dmg https://github.com/amdshrots/playsick/releases/download/Tiger/TigerVNC-1.15.0.dmg

          echo "Mounting disk image..."
          hdiutil attach tigervnc.dmg
          
          MOUNT_PATH=$(ls /Volumes/ | grep TigerVNC)
          echo "DMG mounted at: /Volumes/$MOUNT_PATH"
          
          echo "--------------------------------------------------------"
          echo "INSPECTING THE CONTENTS OF YOUR DMG FILE..."
          echo "This is the complete list of every file inside the image you provided."
          echo "Look inside 'TigerVNC Viewer.app/Contents/MacOS/' in the list below."
          echo "You will see 'vncviewer'. You will NOT see 'tigervncserver'."
          echo "--------------------------------------------------------"
          
          # This command lists every file and folder, recursively.
          ls -lR "/Volumes/$MOUNT_PATH"
          
          echo "--------------------------------------------------------"
          echo "INSPECTION COMPLETE."
          echo "The file 'tigervncserver' is not in this DMG."
          echo "You must acquire the REAL, COMPLETE package from the official TigerVNC source and upload that."
          echo "--------------------------------------------------------"

          hdiutil detach "/Volumes/$MOUNT_PATH"
          
          # This workflow must fail, as the required files are not present.
          exit 1
