# .github/workflows/main.yml

name: macOS Remote Desktop (Definitive)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: '1. Install, Find, and Configure TigerVNC'
        id: setup_vnc # Give this step an ID to reference its outputs
        run: |
          echo "Installing TigerVNC..."
          brew install tiger-vnc

          echo "Querying Homebrew for executable paths..."
          PASSWD_CMD=$(brew list tiger-vnc | grep '/bin/tigervncpasswd$' | head -n 1)
          SERVER_CMD=$(brew list tiger-vnc | grep '/bin/tigervncserver$' | head -n 1)
          
          if [ -z "$PASSWD_CMD" ] || [ -z "$SERVER_CMD" ]; then
            echo "FATAL: Could not find required executables via 'brew list'."
            echo "--- DUMPING ALL INSTALLED FILES FOR tiger-vnc ---"
            brew list tiger-vnc
            echo "-------------------------------------------------"
            exit 1
          fi
          
          echo "Found tigervncpasswd at: $PASSWD_CMD"
          echo "Found tigervncserver at: $SERVER_CMD"

          # Export the discovered paths for the next step to use.
          echo "passwd_cmd=$PASSWD_CMD" >> $GITHUB_OUTPUT
          echo "server_cmd=$SERVER_CMD" >> $GITHUB_OUTPUT

          echo "Configuring VNC password..."
          if [ -z "${{ secrets.VNC_PASSWORD }}" ]; then
            echo "Error: VNC_PASSWORD secret is not set."
            exit 1
          fi
          echo "::add-mask::${{ secrets.VNC_PASSWORD }}"
          
          mkdir -p ~/.vnc
          echo "${{ secrets.VNC_PASSWORD }}" | "$PASSWD_CMD" -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          echo "TigerVNC password configured successfully."

      - name: '2. Start VNC Server and Tunnel'
        run: |
          echo "Starting TigerVNC server using discovered path..."
          # Use the output from the previous step. Steps run sequentially so this is guaranteed to be available.
          "${{ steps.setup_vnc.outputs.server_cmd }}" :1 -localhost no -SecurityTypes VncAuth -PasswordFile ~/.vnc/passwd &
          sleep 5

          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore
          
          nohup ./bore local 5901 --to bore.pub > tunnel.log 2>&1 &
          sleep 5

          echo "--------------------------------------------------------------------"
          echo "SESSION IS NOW ACTIVE."
          cat tunnel.log
          echo "--------------------------------------------------------------------"
          echo "Use the 'bore.pub:PORT' address from the log to connect."
          echo "Password is your VNC_PASSWORD secret. Username is not required."
          
          sleep 21000
