# .github/workflows/main.yml

name: macOS Remote Desktop (Log Capture)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 15 # We don't need the full 6 hours for this test

    steps:
      - name: '1. Enable VNC and Start Log Capture'
        run: |
          echo "::add-mask::${{ secrets.RDP_USER_PASSWORD }}"
          
          echo "Enabling VNC Service for all local users..."
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -allowAccessFor -allUsers -privs -all

          echo "Setting a Master VNC password for the service..."
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw -vncpw "${{ secrets.RDP_USER_PASSWORD }}" -setvnclegacy -vnclegacy yes

          echo "Starting VNC log capture in the background..."
          # This command streams all logs from the ARDAgent process to a file
          log stream --style syslog --predicate 'process == "ARDAgent"' > vnc_server_logs.txt &
          
          echo "VNC service is active. Log capture has begun."

      - name: '2. Create Tunnel and Wait for Login Attempt'
        run: |
          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore

          echo "Starting bore tunnel for VNC (port 5900)..."
          nohup ./bore local 5900 --to bore.pub > tunnel.log 2>&1 &
          sleep 5

          echo "--------------------------------------------------------------------"
          echo "ACTION REQUIRED: ATTEMPT TO LOG IN NOW."
          cat tunnel.log
          echo "Use RealVNC Viewer. Username: 'runner', Password: your secret."
          echo "The login attempt is EXPECTED TO FAIL."
          echo "This workflow will wait for 5 minutes for you to trigger the error."
          echo "After 5 minutes, it will proceed to dump the logs."
          echo "--------------------------------------------------------------------"
          sleep 300 # Wait 5 minutes

      - name: '3. Dump VNC Server Logs'
        run: |
          echo "--------------------------------------------------------------------"
          echo "--- BEGIN VNC SERVER LOG DUMP ---"
          # Check if the log file was created and has content
          if [ -s vnc_server_logs.txt ]; then
            cat vnc_server_logs.txt
          else
            echo "Log file is empty or was not created. No login attempt may have been detected."
          fi
          echo "--- END VNC SERVER LOG DUMP ---"
          echo "--------------------------------------------------------------------"
