# .github/workflows/main.yml

name: macOS Remote Desktop (Definitive)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: '1. Install, Find, and Configure TigerVNC'
        run: |
          echo "Installing TigerVNC..."
          brew install tiger-vnc

          echo "Searching for TigerVNC executables..."
          # Find the exact path of the command, wherever Homebrew put it.
          PASSWD_CMD=$(find /opt/homebrew/Cellar/tiger-vnc -name tigervncpasswd | head -n 1)
          
          if [ -z "$PASSWD_CMD" ]; then
            echo "FATAL: tigervncpasswd command not found after installation."
            exit 1
          fi
          echo "Found tigervncpasswd at: $PASSWD_CMD"

          echo "Configuring VNC password..."
          if [ -z "${{ secrets.VNC_PASSWORD }}" ]; then
            echo "Error: VNC_PASSWORD secret is not set."
            exit 1
          fi
          echo "::add-mask::${{ secrets.VNC_PASSWORD }}"
          
          mkdir -p ~/.vnc
          # Execute the command using its discovered absolute path.
          echo "${{ secrets.VNC_PASSWORD }}" | "$PASSWD_CMD" -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          echo "TigerVNC password configured successfully."

      - name: '2. Start VNC Server and Tunnel'
        run: |
          echo "Searching for TigerVNC server executable..."
          # Find the server command as well.
          SERVER_CMD=$(find /opt/homebrew/Cellar/tiger-vnc -name tigervncserver | head -n 1)

          if [ -z "$SERVER_CMD" ]; then
            echo "FATAL: tigervncserver command not found after installation."
            exit 1
          fi
          echo "Found tigervncserver at: $SERVER_CMD"

          echo "Starting TigerVNC server..."
          "$SERVER_CMD" :1 -localhost no -SecurityTypes VncAuth -PasswordFile ~/.vnc/passwd &
          sleep 5

          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore
          
          nohup ./bore local 5901 --to bore.pub > tunnel.log 2>&1 &
          sleep 5

          echo "--------------------------------------------------------------------"
          echo "SESSION IS NOW ACTIVE."
          cat tunnel.log
          echo "--------------------------------------------------------------------"
          echo "Use the 'bore.pub:PORT' address from the log to connect."
          echo "Password is your VNC_PASSWORD secret. Username is not required."
          
          sleep 21000
