name: macOS Playit.gg + VNC (Headless Only)

on:
  workflow_dispatch:

jobs:
  playit-vnc:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install TigerVNC
        run: |
          brew install tiger-vnc
          brew list tiger-vnc

      - name: Set VNC password
        run: |
          mkdir -p ~/.vnc
          TIGERVNCPASSWD=$(brew --prefix tiger-vnc)/bin/tigervncpasswd
          echo "password" | "$TIGERVNCPASSWD" -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

      - name: Start VNC Server
        run: |
          TIGERVNCSERVER=$(brew --prefix tiger-vnc)/bin/tigervncserver
          "$TIGERVNCSERVER" :1 -geometry 1280x800 -depth 24

      - name: Run Playit agent with secret
        env:
          PLAYIT_SECRET: ${{ secrets.PL }}
        run: |
          ./target/release/playit-cli --secret "$PLAYIT_SECRET"
