# .github/workflows/main.yml

name: macOS Remote Desktop (Final Key)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: '1. Enable VNC Service with a Master Password'
        run: |
          echo "::add-mask::${{ secrets.RDP_USER_PASSWORD }}"
          
          echo "Enabling VNC Service for all local users..."
          # This is the cooperative command: It activates the ARD Agent and grants full control privileges to all existing local users.
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -allowAccessFor -allUsers -privs -all

          echo "Setting a Master VNC password for the service..."
          # This command sets a password for the VNC service itself, which overrides individual user passwords for VNC connections.
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw -vncpw "${{ secrets.RDP_USER_PASSWORD }}" -setvnclegacy -vnclegacy yes

          echo "VNC service is active and configured."

      - name: '2. Create Tunnel and Provide Final Instructions'
        run: |
          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore

          echo "Starting bore tunnel for VNC (port 5900)..."
          nohup ./bore local 5900 --to bore.pub > tunnel.log 2>&1 &
          sleep 5

          echo "--------------------------------------------------------------------"
          echo "SESSION IS NOW ACTIVE. FOLLOW THE FINAL LOGIN PROCEDURE."
          cat tunnel.log
          echo "--------------------------------------------------------------------"
          
          sleep 21000
