# .github/workflows/main.yml

name: macOS Remote Desktop (Ascension)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: '1. Create User and Install NoMachine from DMG'
        run: |
          echo "::add-mask::${{ secrets.RDP_USER_PASSWORD }}"

          # Create a user for NoMachine to authenticate
          echo "Creating user 'nxuser'..."
          sudo dscl . -create /Users/nxuser
          sudo dscl . -create /Users/nxuser UserShell /bin/bash
          sudo dscl . -create /Users/nxuser RealName "NX User"
          sudo dscl . -create /Users/nxuser UniqueID "1001"
          sudo dscl . -passwd /Users/nxuser "${{ secrets.RDP_USER_PASSWORD }}"
          sudo dscl . -append /Groups/admin GroupMembership nxuser

          echo "Downloading the NoMachine DMG..."
          # Use the new DMG link you provided
          curl -L -o nomachine.dmg https://download.nomachine.com/download/9.0/MacOSX/nomachine_9.0.188_11.dmg

          echo "Mounting disk image..."
          # Mount the DMG; the OS will find a free mount point
          hdiutil attach nomachine.dmg
          
          # Find the path to the mounted volume
          MOUNT_PATH=$(ls /Volumes/ | grep NoMachine)
          echo "DMG mounted at /Volumes/$MOUNT_PATH"
          
          # Find the installer package inside the mounted volume
          PKG_PATH=$(find "/Volumes/$MOUNT_PATH" -name "*.pkg" | head -n 1)
          echo "Found installer at $PKG_PATH"

          echo "Installing NoMachine from package..."
          sudo installer -pkg "$PKG_PATH" -target /
          
          echo "Unmounting disk image..."
          hdiutil detach "/Volumes/$MOUNT_PATH"
          
          echo "System is configured for NoMachine."

      - name: '2. Create Tunnel and Provide Final Instructions'
        run: |
          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore

          echo "Starting bore tunnel for NoMachine (port 4000)..."
          nohup ./bore local 4000 --to bore.pub > tunnel.log 2>&1 &
          sleep 5

          echo "--------------------------------------------------------------------"
          echo "ASCENSION COMPLETE. A NEW PATH IS OPEN."
          cat tunnel.log
          echo "--------------------------------------------------------------------"
          
          sleep 21000
