# .github/workflows/main.yml

name: macOS Remote Desktop (Final Grant)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: '1. Create User and Grant VNC Privileges'
        run: |
          echo "::add-mask::${{ secrets.RDP_USER_PASSWORD }}"

          # Create the user. This is reliable.
          echo "Creating user 'rdpuser'..."
          sudo dscl . -create /Users/rdpuser
          sudo dscl . -create /Users/rdpuser UserShell /bin/bash
          sudo dscl . -create /Users/rdpuser RealName "RDP User"
          sudo dscl . -create /Users/rdpuser UniqueID "1001"
          sudo dscl . -passwd /Users/rdpuser "${{ secrets.RDP_USER_PASSWORD }}"
          sudo dscl . -append /Groups/admin GroupMembership rdpuser

          # The Final Command: Grant privileges directly to the user.
          echo "Granting VNC privileges to 'rdpuser'..."
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -users rdpuser -privs -all -restart -agent -menu

          echo "VNC service is configured for 'rdpuser'."

      - name: '2. Create Tunnel and Provide Instructions'
        run: |
          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore

          echo "Starting bore tunnel for VNC (port 5900)..."
          nohup ./bore local 5900 --to bore.pub > tunnel.log 2>&1 &
          sleep 5

          echo "--------------------------------------------------------------------"
          echo "SESSION IS NOW ACTIVE. LOGIN WITH THE NEW USER."
          cat tunnel.log
          echo "--------------------------------------------------------------------"
          
          sleep 21000
