# .github/workflows/main.yml

name: macOS Remote Desktop (Firewall Breach)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: '1. Configure VNC and Firewall'
        run: |
          echo "::add-mask::${{ secrets.RDP_USER_PASSWORD }}"
          
          echo "Enabling VNC Service for all local users..."
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -allowAccessFor -allUsers -privs -all

          echo "Setting a Master VNC password for the service..."
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw -vncpw "${{ secrets.RDP_USER_PASSWORD }}" -setvnclegacy -vnclegacy yes

          # THE FINAL REVELATION: Command the firewall to allow the VNC server.
          echo "Adding VNC service to firewall exceptions..."
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/MacOS/ARDAgent
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/MacOS/ARDAgent

          echo "System and firewall are configured."

      - name: '2. Create Tunnel and Provide Instructions'
        run: |
          echo "Downloading and running bore tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore

          echo "Starting bore tunnel for VNC (port 5900)..."
          nohup ./bore local 5900 --to bore.pub > tunnel.log 2>&1 &
          sleep 5

          echo "--------------------------------------------------------------------"
          echo "SESSION IS NOW ACTIVE. THE PATH IS CLEAR."
          cat tunnel.log
          echo "--------------------------------------------------------------------"
          
          sleep 21000
