# .github/workflows/main.yml

name: macOS Remote Desktop (The Final Truth)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: '1. Install MacPorts and TigerVNC'
        run: |
          echo "Installing MacPorts and TigerVNC..."
          curl -L -O "https://github.com/macports/macports-base/releases/download/v2.10.0/MacPorts-2.10.0-14-Sonoma.pkg"
          sudo installer -pkg MacPorts-2.10.0-14-Sonoma.pkg -target /
          export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
          sudo port -v selfupdate
          sudo port install tigervnc

      - name: '2. Configure and Launch with ABSOLUTE Paths'
        run: |
          echo "::add-mask::${{ secrets.RDP_USER_PASSWORD }}"
          
          # ---- PASTE THE PATHS FROM THE ORACLE'S LOG HERE ----
          PASSWD_CMD="/opt/local/bin/tigervncpasswd" #<-- REPLACE WITH ACTUAL PATH IF DIFFERENT
          SERVER_CMD="/opt/local/bin/tigervncserver" #<-- REPLACE WITH ACTUAL PATH IF DIFFERENT
          
          echo "Configuring VNC password using path: $PASSWD_CMD"
          mkdir -p ~/.vnc
          echo "${{ secrets.RDP_USER_PASSWORD }}" | "$PASSWD_CMD" -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          echo "Starting VNC server using path: $SERVER_CMD"
          "$SERVER_CMD" :1 -localhost no -SecurityTypes VncAuth -PasswordFile ~/.vnc/passwd -fg &
          
      - name: '3. Create Tunnel'
        run: |
          echo "Creating tunnel..."
          curl -LSs https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-apple-darwin.tar.gz | tar -xz
          chmod +x bore
          nohup ./bore local 5901 --to bore.pub > tunnel.log 2>&1 &
          sleep 5
          cat tunnel.log
          sleep 21000
